name: Adhoc
on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  # Allows you to run this workflow manually from the Actions a tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        
        
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          FASTLANE_KEY: ${{ secrets.FASTLANE_PRIVATE_KEY }}
          CONNECT_KEY: ${{ secrets.APPSTORE_CONNECT_P8 }}
        run: |
          echo "$FASTLANE_KEY" > /tmp/fastlane_key
          chmod 600 /tmp/fastlane_key
          echo "$CONNECT_KEY" > /tmp/connect_key
          chmod 600 /tmp/connect_key
          ls -alh /tmp
        
#       - uses: webfactory/ssh-agent@v0.1.1
#         env: 
#           ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
#         with:
#           ssh-private-key: ${{ secrets.FASTLANE_PRIVATE_KEY }}

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.FASTLANE_PRIVATE_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.FASTLANE_KNOWN_HOSTS }}
#           config: ${{ secrets.CONFIG }} # ssh_config; optional
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)

      - name: Deploy iOS Beta to TestFlight via Fastlane
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: ios beta
          subdirectory: 'ios'
        env:
          S3_ACCESS_KEY: '${{ secrets.S3_ACCESS_KEY }}'
          S3_SECRET_ACCESS_KEY: '${{ secrets.S3_SECRET_ACCESS_KEY }}'
          MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
          MATCH_GIT_PRIVATE_KEY: '/tmp/fastlane_key'
          FASTLANE_PASSWORD: '${{ secrets.FASTLANE_PASSWORD }}'
          APPLE_KEY_ID: 'H6Q2FDQYXH'
          APPLE_ISSUER_ID: '0dd77eb6-3776-46a6-84bd-efbf59a2e9a6'
          APPLE_KEY_CONTENT: '${{ secrets.APPSTORE_CONNECT_P8 }}'
          SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER: '${{ secrets.DAVE_PHONE }}'
          # MATCH_AUTHORIZATION: '${{ secrets.MATCH_AUTHORIZATION }}'
          # AUTH_PRIVATE_KEY: '${{ secrets.AUTH_PRIVATE_KEY }}'
          # APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
          # DEVELOPER_APP_ID: '${{ secrets.DEVELOPER_APP_ID }}'
          # DEVELOPER_APP_IDENTIFIER: '${{ secrets.DEVELOPER_APP_IDENTIFIER }}'
          # DEVELOPER_PORTAL_TEAM_ID: '${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}'
          # FASTLANE_APPLE_ID: '${{ secrets.FASTLANE_APPLE_ID }}'
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: '${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}'
          # MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
          # GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
          # PROVISIONING_PROFILE_SPECIFIER: '${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}'
          # TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
          # TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'
#           APPLE_KEY_ID: '${{ secrets.APPLE_KEY_ID }}'
#           APPLE_ISSUER_ID: '${{ secrets.APPLE_ISSUER_ID }}'
#           APPLE_KEY_CONTENT: '${{ secrets.APPLE_KEY_CONTENT }}'
